routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::resource('clientes', 'ClientController', ['except' => ['show', 'destroy']]);
Route::resource('pedidos', 'OrderController');
Route::resource('chamados', 'TicketController');
Route::get('/', 'IndexController@index');

app/Models/Client.php
<?php

namespace App\Models;

class Client extends Model
{
    protected $fillable = ['name', 'email'];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Flows\SaveFlows\ClientSaveFlow;
use App\Models\Client;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Redirect;
use View;

class ClientController extends Controller
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = $this->createQueryString();

        return View::make('clients.index')
            ->withClients($clients->paginate(self::DEFAULT_PAGINATION));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $client = new Client();

        return View::make('clients.create')
            ->withClient($client);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        $client = (new Client())->fill($this->request->input('client'));
        $clientSaveFlow = new ClientSaveFlow($client);
        $clientSaveFlow->validate();

        try {
            $clientSaveFlow->save();

            return Redirect::route('clientes.index')->with('success', 'Cliente ' . $client->email . ' criado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($clientId)
    {
        $client = Client::find($clientId);
        if (!$client) {
            return Redirect::back()->withErrors(['Cliente não encontrado']);
        }

        return View::make('clients.edit')
            ->withClient($client);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($clientId)
    {
        $client = Client::find($clientId);
        if (!$client) {
            return Redirect::back()->withErrors(['Cliente não encontrado']);
        }

        $client->fill($this->request->input('client'));
        $clientSaveFlow = new ClientSaveFlow($client);

        try {
            $clientSaveFlow->save();

            return Redirect::route('clientes.index')->with('success', 'Cliente ' . $client->email . ' atualizado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    protected function createQueryString()
    {
        $clients = Client::query();

        if ($this->request->input('name')) {
            $clients->where('name', 'like', '%' . $this->request->input('name') . '%');
        }

        if ($this->request->input('email')) {
            $clients->where('email', 'like', '%' . $this->request->input('email') . '%');
        }

        return $clients;
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')

<h1>Criar cliente</h1>

@include('clients.form.form', ['route' => ['clientes.store'], 'method' => 'POST'])

@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')

<h1>Editar cliente #{{ $client->getKey() }}</h1>

@include('clients.form.form', ['route' => ['clientes.update', $client->getKey()], 'method' => 'PUT'])

@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')

@include('messages')

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {!! Form::open(['route' => ['clientes.index'], 'method' => 'GET', 'class' => 'form-horizontal']) !!}
            <div class="form-group">
                <div class="col-sm-5">
                    <label for="name" class="control-label">Nome</label>
                    {{ Form::text('name', request('name'), ['class' => 'form-control', 'placeholder' => 'Nome']) }}
                </div>
                <div class="col-sm-5">
                    <label for="email" class="control-label">Email</label>
                    {{ Form::text('email', request('email'), ['class' => 'form-control', 'placeholder' => 'Email']) }}
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-default">Buscar</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
    <div class="col-md-2">
        <a class="btn" href="{{ action('ClientController@create') }}">Novo cliente</a>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Última atualização</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($clients as $client)
                <tr>
                    <td><a href="{{ route('clientes.edit', $client->getKey()) }}">{{ $client->getKey() }}</a></td>
                    <td>{{ $client->name }}</td>
                    <td>{{ $client->email }}</td>
                    <td>{{ Carbon\Carbon::parse($client->updated_at)->format('d/m/Y H:i:s') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {{ $clients->links() }}
    </div>
</div>

@endsection