routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::resource('clientes', 'ClientController', ['except' => ['show', 'destroy']]);
Route::resource('pedidos', 'OrderController');
Route::resource('chamados', 'TicketController');
Route::get('/', 'IndexController@index');

app/Models/Ticket.php
<?php

namespace App\Models;

class Ticket extends Model
{
    protected $fillable = [
        'order_id',
        'title',
        'description',
    ];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Flows\SaveFlows\TicketSaveFlow;
use App\Models\Client;
use App\Models\Order;
use App\Models\Ticket;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Redirect;
use View;

class TicketController extends Controller
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = $this->createQueryString();

        return View::make('tickets.index')
            ->withTickets($tickets->paginate(self::DEFAULT_PAGINATION));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ticket = new Ticket();

        return View::make('tickets.create')
            ->withTicket($ticket);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ticket = (new Ticket())->fill($this->request->input('ticket'));
        $ticketSaveFlow = new TicketSaveFlow(
            $ticket,
            Order::firstOrNew($this->request->input('ticket.order')),
            Client::firstOrNew($this->request->input('ticket.client'))
        );
        $ticketSaveFlow->validate();

        try {
            $ticketSaveFlow->save();

            return Redirect::route('chamados.index')->with('success', 'Chamado ' . $ticket->getKey() . ' criado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($ticketId)
    {
        $ticket = Ticket::find($ticketId);
        if (!$ticket) {
            return Redirect::back()->withErrors(['Chamado não encontrado']);
        }

        return View::make('tickets.edit')
            ->withTicket($ticket);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $ticketId)
    {
        $ticket = Ticket::find($ticketId);
        if (!$ticket) {
            return Redirect::back()->withErrors(['Chamado não encontrado']);
        }

        $ticket->fill($this->request->input('ticket'));
        $ticketSaveFlow = new TicketSaveFlow(
            $ticket,
            Order::firstOrNew($this->request->input('ticket.order')),
            Client::firstOrNew($this->request->input('ticket.client'))
        );
        $ticketSaveFlow->validate();

        try {
            $ticketSaveFlow->save();

            return Redirect::route('chamados.index')->with('success', 'Chamado ' . $ticket->getKey() . ' atualizado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    protected function createQueryString()
    {
        $tickets = Ticket::query();

        if ($this->request->input('email')) {
            $tickets->whereHas('order.client', function ($q) {
                $q->where('email', 'like', '%' . $this->request->input('email') . '%');
            });
        }

        if ($this->request->input('order')) {
            $tickets->whereHas('order', function ($q) {
                $q->where('id', '=', $this->request->input('order'));
            });
        }

        return $tickets;
    }
}

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('content')

<h1>Criar chamado</h1>

@include('tickets.form.form', ['route' => ['chamados.store'], 'method' => 'POST'])

@endsection

resources/views/tickets/edit.blade.php
@extends('layouts.app')

@section('content')

<h1>Editar chamado #{{ $ticket->getKey() }}</h1>

@include('tickets.form.form', ['route' => ['chamados.update', $ticket->getKey()], 'method' => 'PUT'])

@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')

@include('messages')

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {!! Form::open(['route' => ['chamados.index'], 'method' => 'GET', 'class' => 'form-horizontal']) !!}
            <div class="form-group">
                <div class="col-sm-5">
                    <label for="email" class="control-label">Email (Cliente)</label>
                    {{ Form::text('email', request('email'), ['class' => 'form-control', 'placeholder' => 'Email']) }}
                </div>
                <div class="col-sm-5">
                    <label for="order" class="control-label">Pedido</label>
                    {{ Form::number('order', request('order'), ['class' => 'form-control', 'placeholder' => 'Pedido', 'min' => 0]) }}
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-default">Buscar</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
    <div class="col-md-2">
        <a class="btn" href="{{ action('TicketController@create') }}">Novo chamado</a>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Pedido</th>
                    <th>Titulo</th>
                    <th>Última atualização</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($tickets as $ticket)
                <tr>
                    <td><a href="{{ route('chamados.edit', $ticket->getKey()) }}">{{ $ticket->getKey() }}</a></td>
                    <td>{{ $ticket->order->client->name }}</td>
                    <td>{{ $ticket->order->client->email }}</td>
                    <td>{{ $ticket->order->getKey() }}</td>
                    <td>{{ $ticket->title }}</td>
                    <td>{{ Carbon\Carbon::parse($ticket->updated_at)->format('d/m/Y H:i:s') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {{ $tickets->links() }}
    </div>
</div>

@endsection