routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::resource('clientes', 'ClientController', ['except' => ['show', 'destroy']]);
Route::resource('pedidos', 'OrderController');
Route::resource('chamados', 'TicketController');
Route::get('/', 'IndexController@index');

app/Models/Order.php
<?php

namespace App\Models;

class Order extends Model
{
    protected $fillable = ['id', 'client_id'];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Flows\SaveFlows\OrderSaveFlow;
use App\Models\Client;
use App\Models\Order;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Redirect;
use View;

class OrderController extends Controller
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->createQueryString();

        return View::make('orders.index')
            ->withOrders($orders->paginate(self::DEFAULT_PAGINATION));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $order = new Order();

        return View::make('orders.create')
            ->withOrder($order);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = new Order();
        $orderSaveFlow = new OrderSaveFlow($order, Client::firstOrNew($this->request->input('order.client')));
        $orderSaveFlow->validate();

        try {
            $orderSaveFlow->save();

            return Redirect::route('pedidos.index')->with('success', 'Pedido ' . $order->getKey() . ' criado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($orderId)
    {
        $order = Order::find($orderId);
        if (!$order) {
            return Redirect::back()->withErrors(['Pedido não encontrado']);
        }

        return View::make('orders.edit')
            ->withOrder($order);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $orderId)
    {
        $order = Order::find($orderId);
        if (!$order) {
            return Redirect::back()->withErrors(['Pedido não encontrado']);
        }

        $orderSaveFlow = new OrderSaveFlow($order, Client::firstOrNew($this->request->input('order.client')));
        $orderSaveFlow->validate();

        try {
            $orderSaveFlow->save();

            return Redirect::route('pedidos.index')->with('success', 'Pedido ' . $order->getKey() . ' atualizado com sucesso');
        } catch (QueryException $e) {
            return Redirect::back()->withErrors([$e->getMessage()]);
        }
    }

    protected function createQueryString()
    {
        $orders = Order::query();

        if ($this->request->input('email')) {
            $orders->whereHas('client', function ($q) {
                $q->where('email', 'like', '%' . $this->request->input('email') . '%');
            });
        }

        if ($this->request->input('order')) {
            $orders->where('id', '=', $this->request->input('order'));
        }

        return $orders;
    }
}

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')

<h1>Criar pedido</h1>

@include('orders.form.form', ['route' => ['pedidos.store'], 'method' => 'POST'])

@endsection

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')

<h1>Editar pedido #{{ $order->getKey() }}</h1>

@include('orders.form.form', ['route' => ['pedidos.update', $order->getKey()], 'method' => 'PUT'])

@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')

@include('messages')

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {!! Form::open(['route' => ['pedidos.index'], 'method' => 'GET', 'class' => 'form-horizontal']) !!}
            <div class="form-group">
                <div class="col-sm-5">
                    <label for="email" class="control-label">Email (Cliente)</label>
                    {{ Form::text('email', request('email'), ['class' => 'form-control', 'placeholder' => 'Email']) }}
                </div>
                <div class="col-sm-5">
                    <label for="order" class="control-label">Pedido</label>
                    {{ Form::number('order', request('order'), ['class' => 'form-control', 'placeholder' => 'Pedido', 'min' => 0]) }}
                </div>
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-default">Buscar</button>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
    <div class="col-md-2">
        <a class="btn" href="{{ action('OrderController@create') }}">Novo pedido</a>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Email (Cliente)</th>
                    <th>Última atualização</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($orders as $order)
                <tr>
                    <td><a href="{{ route('pedidos.edit', $order->getKey()) }}">{{ $order->getKey() }}</a></td>
                    <td>{{ $order->client->email }}</td>
                    <td>{{ Carbon\Carbon::parse($order->updated_at)->format('d/m/Y H:i:s') }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-2 col-md-8">
        {{ $orders->links() }}
    </div>
</div>

@endsection